apiVersion: v1
kind: Service
metadata:
  name: veridra-backend
  labels:
    app: veridra-backend
spec:
  type: ClusterIP
  selector:
    app: veridra-backend
  ports:
    - protocol: TCP
      port: 80        # The service port
      targetPort: 8000  # The container port
